apiVersion : apps/v1
kind: Deployment

metadata:
  name: devops-test-deployment
  labels:
    app: devops-test-app

spec:
  selector:
    matchLabels:
      app: devops-test-app
  template:
    metadata:
      labels:
        app: devops-test-app
    spec:
      containers:

      volumes:
      - name: local-volume
        persistentVolumeClaim:
          claimName: pvc-local